### ISSUE TITLE
Explanation about the `node.ws.` variable

### ISSUE THREAD

**Issue by danijelTxFusion** [celestiaorg/helm-charts#48]
I am struggling to figure out what is `node.ws` varible is used for? I created the certificate secret using `cert-manager`, but can it be used for configuring TLS for `rpc`, `rest` and `ws` endpoints? I see the volume is attached to the node pod, but I can't figure out how to configure celestia node to use that certificate.

```yaml
 node:
   ws:
        tls:
          enabled: true
          ## A secret must be available in the cluster with the following format:
          ## - name: <secret-name>
          ## - items:
          ##     - key: tls.cert
          ##     - key: tls.key
          secret:
            name: celestia-cert  # created by cert-manager
```
